[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[project]
name = "fluxion"
version = "0.1.0"  # Make sure to include this line
dynamic = ["version"]
description = "A simple, fast, and flexible agentic flow creation library."