name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Install and Test
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        sudo apt install portaudio19-dev
        python -m pip install --upgrade pip setuptools
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    # Step 4: Run Unit Tests with Coverage
    - name: Run Unit Tests with Coverage
      id: test
      run: |
        pytest tests/ --cov=src --cov-report=term --cov-report=term-missing > coverage_output.txt

    # Step 5: Post Coverage to PR
    - name: Post Coverage Comment
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const coverage = fs.readFileSync('coverage_output.txt', 'utf8');
          github.rest.issues.createComment({
            ...context.repo,
            issue_number: context.payload.pull_request.number,
            body: `### Coverage Report\n\`\`\`\n${coverage}\n\`\`\``
          });
