name: Automated Versioning and Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump2version setuptools wheel

      - name: Fetch All Tags
        run: git fetch --all --tags

      - name: Determine Version Bump
        id: version_bump
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "0.0.0")
          echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV

          if git log --pretty=format:%s "$LAST_TAG"...HEAD | grep -q '^feat'; then
            VERSION_BUMP=minor
          elif git log --pretty=format:%s "$LAST_TAG"...HEAD | grep -q '^fix'; then
            VERSION_BUMP=patch
          else
            VERSION_BUMP=patch
          fi
          echo "VERSION_BUMP=$VERSION_BUMP" >> $GITHUB_ENV

      - name: Bump Version
        run: |
          bump2version --current-version $LAST_TAG $VERSION_BUMP --allow-dirty
        env:
          VERSION_BUMP: ${{ env.VERSION_BUMP }}

      - name: Push Changes and Tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git push origin main --tags

      - name: Get New Version
        id: get_version
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$VERSION" --notes "Automated release for version $VERSION."
